apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.deployment.gateway}}
  name: {{ .deploymentName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "gateway.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.labels" . | nindent 8 }}
        {{- include "common.labels" $ | nindent 8 }}
    spec:
      containers:
      - name: {{ .containerName }}
        image: {{ .imageName }}:{{ .imageTag | default "latest" }}
        imagePullPolicy: {{ .imagePullPolicy }}
        ports:
        - containerPort: {{ .containerPort }}
  {{- end }}       
