apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.gateway.serviceName }}
spec:
  type: {{ .Values.service.gateway.serviceType }}
  selector:
    {{- include "gateway.labels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.gateway.serviceProtocol }}
      port: {{ .Values.service.gateway.servicePort }}
      targetPort: {{ .Values.service.gateway.serviceTargetPort }}
      nodePort: {{ .Values.service.gateway.serviceNodePort }}

